services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./label-studio:/label-studio/data
    environment:
      - LABEL_STUDIO_USERNAME=admin@admi.com
      - LABEL_STUDIO_PASSWORD=adminadmin
    command: label-studio --log-level DEBUG