[project]
name = "scored"
version = "0.1.0"
description = "Single camera dart scoring system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gui",
    "opencv-python>=4.13.0.92",
]

[tool.uv.workspace]
members = [
    "scored_lib",
    "gui",
    "nn",
]

[tool.uv.sources]
gui = { workspace = true }

[dependency-groups]
dev = [
    "black>=26.3.1",
    "isort>=8.0.1",
]

[tool.black]
line-length = 100
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 100