[tool.poetry]
name = "monorepo-dev"
version = "0.0.0"
description = "Dev dependencies for the scored monorepo"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.group.dev.dependencies]
black = "25.1.0"
isort = "6.0.1"
poethepoet = "^0.37.0"

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
known_first_party = ["scored", "gui", "ml"]

[tool.pylint.format]
max-line-length = "100"

[tool.poe.tasks]
format_gui = "black projects/gui/"
format_lib = "black projects/lib/"
format_ml = "black projects/ml/"
sort_gui = "isort projects/gui/"
sort_lib = "isort projects/lib/"
sort_ml = "isort projects/ml/"