[project]
name = "gui"
version = "0.1.0"
description = "a gui for the scored project to visualize the results and interact with the system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "darkdetect>=0.8.0",
    "pillow>=12.3.0",
    "pywinstyles>=1.8",
    "scored-lib",
    "simple-parsing>=0.1.8",
    "sv-ttk>=2.6.1",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[tool.uv.sources]
scored-lib = { workspace = true }


[project.scripts]
scored-gui = "gui.main:main"
