[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "scored-lib"
version = "0.0.0"
description = "Shared library for Scored projects"
authors = ["DerPenz"]
license = "MIT"
readme = "README.md"
keywords = ["scored"]

[tool.poetry.dependencies]
python = ">=3.11"
numpy = "^2.3.2"

[[tool.poetry.packages]]
include = "scored"